#ifndef __QR_QRTYPES_H__
#define __QR_QRTYPES_H__

#include <stdint.h>

typedef enum {
	QR_VERSION_INVALID = -1,
	QR_VERSION_AUTO = 0,

	QR_VERSION_1,
	QR_VERSION_2,
	QR_VERSION_3,
	QR_VERSION_4,
	QR_VERSION_5,
	QR_VERSION_6,
	QR_VERSION_7,
	QR_VERSION_8,
	QR_VERSION_9,
	QR_VERSION_10,
	QR_VERSION_11,
	QR_VERSION_12,
	QR_VERSION_13,
	QR_VERSION_14,
	QR_VERSION_15,
	QR_VERSION_16,
	QR_VERSION_17,
	QR_VERSION_18,
	QR_VERSION_19,
	QR_VERSION_20,
	QR_VERSION_21,
	QR_VERSION_22,
	QR_VERSION_23,
	QR_VERSION_24,
	QR_VERSION_25,
	QR_VERSION_26,
	QR_VERSION_27,
	QR_VERSION_28,
	QR_VERSION_29,
	QR_VERSION_30,
	QR_VERSION_31,
	QR_VERSION_32,
	QR_VERSION_33,
	QR_VERSION_34,
	QR_VERSION_35,
	QR_VERSION_36,
	QR_VERSION_37,
	QR_VERSION_38,
	QR_VERSION_39,
	QR_VERSION_40,

	QR_VERSION_M1,
	QR_VERSION_M2,
	QR_VERSION_M3,
	QR_VERSION_M4,
} qr_version_t;

typedef enum {
	QR_ERRORLEVEL_INVALID = -1,

	QR_ERRORLEVEL_L,
	QR_ERRORLEVEL_M,
	QR_ERRORLEVEL_Q,
	QR_ERRORLEVEL_H,
} qr_errorlevel_t;

typedef enum {
	QR_MASKPATTERN_INVALID = -1,

	QR_MASKPATTERN_0,
	QR_MASKPATTERN_1,
	QR_MASKPATTERN_2,
	QR_MASKPATTERN_3,
	QR_MASKPATTERN_4,
	QR_MASKPATTERN_5,
	QR_MASKPATTERN_6,
	QR_MASKPATTERN_7,

	QR_MASKPATTERN_NONE,
	QR_MASKPATTERN_ALL,

	QR_MASKPATTERN_AUTO,
} qr_maskpattern_t;

#define IS_MQR(version) (QR_VERSION_M1 <= (version) && (version) <= QR_VERSION_M4)
#define IS_QR(version)  (QR_VERSION_1 <= (version) && (version) <= QR_VERSION_40)

#endif /* __QR_QRTYPES_H__*/
