name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Make
          run: make all

        - name: Install
          run: PREFIX=/usr/local/bin make install

        - name: Run & test
          run: |
            OUTPUT=$(qrean -f TXT -t rmqr Hello)
            EXPECTED=$(cat << EOS
            ███████████████████████████████████████████████████████████████████
            ███████████████████████████████████████████████████████████████████
            ████ ▄▄▄▄▄ █ █ ▀ █ ▀▄▀ ▄ █▄▀ █▄█ █▄▀ █▄█▄█ ▄ █▄█ ▀ █ ▀ █▄▀▄█ ▄ ████
            ████ █   █ █ ▀█▄███▄ █▄▄   ▄▄▄▄ █▄▀█▀▄▄ ▀ ▄▄  ▀█▄ ▄▀█▄  ▄▀ ▄▄▄ ████
            ████ █▄▄▄█ █▀▄ ██▀ ██▀ ▄  ▄▀▀██ ▀▀▀█▄ ▀█   ▄  ▄█▀  ██ ▄ ▄█ █▄█ ████
            ████▄▄▄▄▄▄▄█▄█▄█▄█▄█▄█▄▄▄█▄█▄█▄█▄█▄█▄█▄█▄█▄▄▄█▄█▄█▄█▄█▄█▄█▄▄▄▄▄████
            ███████████████████████████████████████████████████████████████████
            ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
            EOS
            )
            test "$OUTPUT" = "$EXPECTED"
